#+title: Minimal Intercal C Language Specification
#+author: Qifan Wang

This is a draft

* Summary

** Currently supported

Note that the tokenizer assumes the host Common Lisp has
been properly setup that the stream converts =\n= or =\r\n=
to a dedicated =#\Newline= character according to platform's
convention.

- All keywords from ISO C99
- C99 decimal and octal integers
- C99 identifiers
- All C99 punctuactors except =##= and =%:%:=, they are
  only used in preprocessor.
- =/* */= and =//= comment

** Planned but not implemented

At current stage, these can result in unexpected error
been reported while lexing. There might be a chance they get
implemented when parser has been started, or maybe not.

- Strings and character literals
- Token =...=

TBD

* Specification

** Lexical Elements

Note that ='\\'= appears in the grammar actually denotes a single =\=
character.

Tokens are optionally separated by one or more whitespaces.

Identifiers, keywords, or constants must be delimited by whitespaces,
comments or punctuators.

#+BEGIN_SRC
  token:
    keyword
    identifier
    constant
    punctuator
    comment
    preprocessor-instruction
  whitespace:
    space
    tab
    newline
  space:   '\s'
  tab:     '\t'
  newline: '\n'
#+END_SRC

*** Keywords

They are:
- =auto=
- =break=
- =case=
- =char=
- =const=
- =continue=
- =default=
- =do=
- =double=
- =else=
- =enum=
- =extern=
- =float=
- =for=
- =goto=
- =if=
- =inline=
- =int=
- =long=
- =register=
- =restrict=
- =return=
- =short=
- =signed=
- =sizeof=
- =static=
- =struct=
- =switch=
- =typedef=
- =union=
- =unsigned=
- =void=
- =volatile=
- =while=
- =_Bool=
- =_Complex=
- =_Imaginary=

*** Identifier

#+BEGIN_SRC
  identifier:
    nondigit
    identifier nondigit
    identifier digit
  nondigit: one of
    '_' 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P'
    'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z'
    'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p'
    'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z'
  digit: one of
    '0' '1' '2' '3' '4' '5' '6' '7' '8' '9'
#+END_SRC

*** Constant



*** Comment syntax and Preprocessor instructions

#+BEGIN_SRC
  comment:
    multiline-comment
    singleline-comment
  multiline-comment:
    '/*' "text that does not contain '*/'" '*/'
  singleline-comment:
    '//' [ "text that does not contain '\n'" '\\' '\n' ]*
           "text that does not contain '\n'" '\n'
  preprocessor-instruction:
    '#' [ "text that does not contain '\n'" '\\' '\n' ]*
          "text that does not contain '\n'" '\n'
#+END_SRC

A multi-line comment starts with =/*= and can contain any character
sequences except the ending sequence, and ends with =*/=.

A single line comment starts with =//= and ends with a newline
that is not prefixed by the line continuation character =\=.

Preprocessor instructions is similar to single line comment
except starts with =#=.
